services:

  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - waha_data:/app/.sessions
    environment:
      WAHA_LOG_FORMAT: JSON
      WHATSAPP_HOOK_URL: http://api:8000/waha/webhook
      WHATSAPP_HOOK_EVENTS: message,session.status
      WHATSAPP_HOOK_RETRIES_ATTEMPTS: 4
      WHATSAPP_HOOK_RETRIES_DELAY_SECONDS: 3
      WAHA_SESSION_NAME: default
      WAHA_API_URL: http://waha:3000/api
      #WAHA_WEBHOOK_VERIFY_TOKEN: your_verify_token
      #WAHA_WEBHOOK_SECRET: your_webhook_secret
      WAHA_TIMEZONE: America/Sao_Paulo
      WAHA_LOCALE: pt-BR
      WAHA_LOG_LEVEL: info
      WAHA_LOG_PRETTY: "false"
      WAHA_LOG_COLOR: "false"
      WAHA_LOG_FILE: /app/waha.log
      WAHA_LOG_MAX_SIZE: 10m
      WAHA_LOG_MAX_FILES: 5
      WAHA_LOG_CONSOLE: "true"
      WAHA_LOG_JSON: "true"   
  
  rabbitmq:
    image: rabbitmq:4.1.3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/workspace:cached
    command: tail -f /dev/null
    ports:
      - '8000:8000' 
    environment:
      WAHA_API_URL: http://waha:3000/api
      WAHA_SESSION_NAME: default

volumes:
  waha_data:
  rabbitmq_data:
  redis_data:
            
           